server:
  port: 7001
#Eureka
eureka:
  instance:
    hostname: eureka7001.com #Eureak服务端实例名称
  client:
    register-with-eureka: false #表示是否在注册中心注册本身 默认为true
    fetch-registry: false #如果为false则表示自己为注册中心
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/