server:
  port: 8081
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp